- backend_WIP.py
Adding the first version of the backend file, work in progress
> [WIP] First version of the backend file

- backend.py
Fixes: https://github.com/PyLadiesCZ/roboprojekt/issues/29
> Odstraněno WIP z názvu souboru

- frontend.py
- game.py
takto mi fungoval kod spolu s backendem, vim že tam většina nepatří, zajímá mě zda pak řádky 5-25 pak 46+ patří do game.py?
> [WIP] First version of the frontend file

- backend.py
Adding documentation according to https://github.com/PyLadiesCZ/roboprojekt/issues/28
> Adding more complex comments to the backend file

- test_backend.py
Test neřeší aktuální kod. Smazala jsem ho, aby nepadal Travis.
> Delete the test

- maps/test_3.json
Předělaná testovací mapa č. 3. kvůli #55
Vrstvy, otočení, startovací políčka.
> Upgrade map (add starting squares)

- backend.py
Change quotes according to convention
> Change documentation strings

- README.md
> Add pyglet to requirements

- frontend.py
- game.py
Rearrangement of comments in Frontend and Game, minor changes in code (move map size definition from game to frontend)
> Rearrangement of comments in Frontend and Game, minor changes in code

- backend.py
- frontend.py
- test_backend.py
New structure of data in class State(board, robots):
Board is now dictionary with coordinates as a key and the value
for certain key now contain all tiles with the same coordinates.
For example: {(0,0): [Tile, Tile], (0,1): [Tile] ... }
Robots remember now their location on the board.
Tile(0,0) also removed. Issue 73 done.
> Change of data structure

- backend.py
- game.py
- test_backend.py
Přidala jsem metodu a robotci se hýbou po 3 sec o 2 políčka.
> Add method move_robot

- backend.py
- frontend.py
- game.py
- test_backend.py
It works in a meaning - it does the same things as before.
Uploaded to have something to discuss about.
I'm still drawing and rewriting it every half an hour according to what I find in the docs. Still feeling more lost than found. 
Corresponding issue #106
> Add class Direction

- backend.py
Sirotek po odstranenni zbytecne zavorky.
> Change self.rotation to  self.direction in `Tile.__repr__()`

- export_img.py
Soubor pouštět v adresáři kde jsou svg obrázky k převodu.
> export svg to png

- test_backend.py
The next iteration over tests:
- more logical positive and negative check of the tile types on the map (instead of long list of integers)
- add forgotten Robot.rotate() method test
It can be merged now, but I am going to continuously work on redesign of old and adding new tests.
> Add + redo tests

- export_img.py
funguje již jak má, převede všechny obrázky ve všech podsložkách v img
> finální úprava export_img

- backend.py
- game.py
- test_backend.py
První verze řešení issue #125. Zatím není dořešený pohyb na pásech, ale jinak to snad funguje. Budu v tom dál pokračovat.
> Add pushing of robot by other robot

- game.py
- test_backend.py
- test_loading.py
+ Add test for RepairTile
Please merge ;)
> Divide tests into two logical parts (loading - backend functions)

- backend.py
- game.py
- util.py
Kontrola díry po pohybu robota přesunuta přímo do metod robota umožňující pohyb (`walk` a `move`). 
Přidáno vyhodocení robotova atributu `inactive` na základě jeho souřadnic.
> Move HoleTile check to robot's move and walk methods

- backend.py
- test_backend.py
"""
rename get_robots_to_start to initial_robots_list
change coordinates of inactive robot (-1,-1) to `None`
"""
> rename get_robots_to_start to create_robots

- backend.py
rename check_wall to check_the_absence_of_a_wall
adjust function check_the_absence_of_a_wall
> rename check_wall to check_the_absence_of_a_wall

- backend.py
- util.py
- adjust `def walk` function 
- change `transform_direction` as a method to function
Další úkoly z https://github.com/PyLadiesCZ/roboprojekt/issues/172
> adjust `def walk` function+change transform_direction

- frontend.py
- game.py
- interface_frontend.py
Dva malé úkoly z https://github.com/PyLadiesCZ/roboprojekt/issues/172
> Rename init_window to create_window and draw_board to draw_state

- backend.py
- frontend.py
- test_backend.py
+ fix load_robots in frontend
+ fix docstring in test_backend
> fix walk, move method

- backend.py
- frontend.py
- test_backend.py
+ fix docstring in tests_backend.py
> rename sizes to tile_count

- loading.py
- util.py
https://github.com/PyLadiesCZ/roboprojekt/issues/172
> rename select_tile to create_tile_subclass

- backend.py
robot insted of index of robot
> remove robot_in_the_way_index

- backend.py
- frontend.py
- test_backend.py
"""
from Robot init removed robot paths, add name
add method as_dict for robot and state(WIP)
add function get_robot_names
get_robots_paths moved to frontend
"""
> Create robot name

- interface.py
- interface_frontend.py
https://github.com/PyLadiesCZ/roboprojekt/issues/220
> adjust robot_data, load robot image

- backend.py
- client_receiver.py
- client_sender.py
- requirements.txt
- server.py
adjust as_dict methods in backend.py
> add server.py, client_receiver.py, client_sender.py

- backend.py
- client_receiver.py
- loading.py
BACKEND - function state_from_dict, robot_from_dict
LOADING - get_board divided into two function - get_board and board_from_dict
> WIP: Client create State from JSON received from server

- backend.py
- client_receiver.py
- connection asyncio + pyglet
- adjust robot_from_dict, state_from_dict
> Connection asyncio + pyglet

- client_interface.py
- interface.py
- interface_frontend.py
- server.py
interface_frontend.py - Press "k" on keyboard print JSON of selected cards
create client_interface.py - connection with pyglet, send json to server.
> Client_interface

- client_interface.py
- interface.py
přidána metoda `to_server_as_dict` a při spuštění client_interface.py posílá json o svém stavu serveru.
Přijde mi to funkční, tak mrkněte.
> Client interface send data about his state

- client_interface.py
- server.py
Server na začátku pošle jen robot.name místo robota
Client_interface si pokaždé self.state.robot aktualizuje z příchozí zprávy stavu hry.
> Change loading robot data

- client_interface.py
- client_receiver.py
- run_all.py
- run_all_clients.py
- server.py
- clientům přidána metoda main
- pro testovací účely k apply_all_effect přidán run_all.py která spustí najednou receivera i interface, do budoucna se může upravit dle potřeby.
A ještě jsem musela znovu upravit odstranění toho json.dumps, protože se to sice upravilo v jednom PR, ale jak se tvořila třída Server, která se mergnula tak tam to nebylo.
> def main()

- backend.py
- server.py
Malé zkrácení kodu na serveru, nová metoda v backendu all_selected
> All_selected

- server.py
- porovnání čísla herního kola klienta a stavu
- pokud souhlasí, provedou se efekty
> Check game round

- interface_frontend.py
změna vytváření Label v interface_frontend.py
> Change create label

- backend.py
- server.py
https://github.com/PyLadiesCZ/roboprojekt/issues/338
> Correction drawing life hearts

- interface.py
- tests/test_interface.py
> Fix cursor

- client_interface.py
> Correction draw winner crown

- client_interface.py
- interface_frontend.py
Funguje vybírání karet, power down a potvrzení.
Funguje i změna pozice kurzoru, takže můžete libovolně měnit jeho pozici.
Pokud chce vrátit jednu kartu, klikne na ni a potom na čtvereček - Return one cards: I. Případně rovnou kliknout na jinou kartu, kterou ji chce nahradit.
Všechny karty se vrátí když se klikne na ten čtvereček kde je napsané Return all cards: O
> Interface is handled by mouse

- backend.py
- interface_frontend.py
Robot se odstraní ze seznamu robotů, pokud má permament damages 10.
Interface se vykreslí Game over.
Plus v interface_frontend opraveno None robot, měla by řešit https://github.com/PyLadiesCZ/roboprojekt/issues/377
> Robot die after 10 permanent damages

- interface_frontend.py
Malá úprava, zjednodušení kódu.
f"00:{seconds_left:02}"  - 02 znamená že se číslo bude mít vždy 2 znaky a pokud je to jedno číslo, doplní se před něj 0.
> Change format of timer

- backend.py
- interface_frontend.py
- robots.yaml
- tests/test_backend.py
V souboru robots.yaml jsou jména robotů, které se vykreslují, aby se nemusely přejmenovávat soubory. Můžeme je měnit dle libosti, do budoucna se přidají i vlastnosti robotů, popisek, když si bude hráč vybírat.
V backendu tedy přidán nový atribut `displayed_name` které se vykresluje ve frontendu.
> Displayed name of robot

- robots.yaml
> Correction name in robots.yaml

- interface_frontend.py
upraveno, mrkni jestli už je to dobrý @befeleme
> Adjust draw other robots

- README.md
Fixes #412 
Upravila jsem README. Predpokladam, ze se jeste neco zmeni do uterka, resp. budeme tam chtit neco pridat, stavajici verze je ale v souladu s dnesnim masterem.
> Update readme to reflect the current state of the project.

- client_interface.py
- client_receiver.py
- interface_frontend.py
Už se vítěz vykresluje pouze jednou.
Řeší https://github.com/PyLadiesCZ/roboprojekt/issues/413
Joo a špatně se mi vykresloval vítěz tak jen posunutí souřadnic ve frontendu
> Draw winner once

- client_interface.py
- interface_frontend.py
solve https://github.com/PyLadiesCZ/roboprojekt/issues/417
> Solve bug - click on blocked card

- backend.py
Fixes #423
Vypada to, ze nam chybelo logovani otoceni. Po pridani logu se to zda provadet korektne.
> Add missing log for rotation.

- backend.py
- server.py
Při spouštění serveru lze zadat volitelný argument počet hráčů. Na základě toho se vytvoří startovací políčka a počet hráčů.
> argument players

- interface_frontend.py
Už jsou dole vidět jména ostatních robotů/hráčů :-)
> Zobrazení jmen robotů
